[[redirects]]
  from = "/proxy/*"
  to = "https://www.fingerorder.ga/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "/build"
  command = "CI= npm run build"
  base = "/"