[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/proxy/*"
  to = "https://www.fingerorder.ga/:splat"  
  status = 200
  force = true

[build]
publish = "publish"
command = "npm run build"